name: motion_photos
description: A Dart package for detecting and extracting Motion Photo from a image file.
version: 1.0.0
homepage: https://ente.io
repository: https://github.com/ente-io/motion_photos

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  xml: ^6.2.2

dev_dependencies:
  lints: any
  test: ^1.17.0
