name: Flutter/Dart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  flutter_version: "3.19.x"  # Latest stable Flutter version
  java_version: "12.x"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.java_version }}

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install example dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Run Formatter
        run: dart format --output=none --set-exit-if-changed .

      - name: Run Analyzer
        run: dart analyze --fatal-infos

      - name: Run tests
        run: flutter test # This will run tests in both the main package and example